import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen">
          <Nav />
          <div className="flex">
            <SideNav />
            <div className="w-[100%] pt-[1rem] px-[2rem]">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
