// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "userData",
    columns: [
      { name: "name", type: "string" },
      { name: "userId", type: "string", notNull: true, defaultValue: "null" },
      { name: "studentId", type: "string", unique: true },
      { name: "email", type: "email", unique: true },
      {
        name: "yearlevel",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type UserData = InferredTypes["userData"];
export type UserDataRecord = UserData & XataRecord;

export type DatabaseSchema = {
  userData: UserDataRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://ivanotch-s-workspace-jhoi6b.us-east-1.xata.sh/db/earist-org-saya",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
